import { CartProvider } from '../context/CartContext';
import {ClerkProvider} from '@clerk/nextjs';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { ComparisonProvider } from '../context/ComparisonContext';  



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dealport E-commerce",
  description: "Generated by tarabhai ",
};


export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ComparisonProvider>
            <CartProvider>
              {children}
            </CartProvider>
          </ComparisonProvider>
          <ToastContainer position="bottom-right" autoClose={5000} />
        </body>
      </html>
    </ClerkProvider>
  );
}
